server:
  port: 8099
spring:
  datasource:
    url: jdbc:mysql://localhost/xiatian?useUnicode=true&characterEncoding=utf-8
    password: 123456
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filter: stat
  jpa:
    show-sql: true

mybatis:
  type-aliases-package: cn.gson.xiatian.model.pojos
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
    cache-enabled: true


